### ISSUE TITLE
When Inactive app still requires unlock when unlocking phone.

### ISSUE THREAD

**Issue by damacus** [mclear/Android_NFC_Ring_Unlock#30] opened 2014-01-10 13:10 UTC
As above. I've set the app to "inactive" yet I've had it fire up 3 maybe 4 times in the past 2 days.

**Comment by JohnMcLear** [comment] 2014-01-10 14:59
I'm unable to replicate this bug, have had the app installed for months and not had this issue.  Possibly phone related?  What handset are you using?

Can you please confirm how you are setting it to "inactive" ?  Is there a specific way you can replicate this issue?  Perhaps try turning off/on your phone a number of times until it happens?  There must be a trigger..

**Comment by damacus** [comment] 2014-01-10 15:32
There's a switch in one of the options, which I've set to "inactive"  I'm
using the nexus 4

**Comment by JohnMcLear** [comment] 2014-01-10 15:35
Can you let us know which option please?  Specifically the screen title :) Thanks

**Comment by damacus** [comment] 2014-01-10 15:43
Ah!
Device security - - > inactive

**Comment by r2DoesInc** [comment] 2014-01-10 15:46
I do not think that this is possible. I would need to have some way to replicate it.

**Comment by damacus** [comment] 2014-01-10 15:51
The only time I've had it happen is when the phone's been idle to a long
time. Then it seems to activate it.

Problem is it's very sporadic. (and I'm also having problems with the
unlock with email option possibly user error at the moment).

I am right in thinking that option should disable the app?

**Comment by r2DoesInc** [comment] 2014-01-10 15:55
Exactly. If this is not disabling the app, then it is a big issue.
Unfortunatly, I do not see how this could be the case.

**Comment by fgsguedes** [comment] 2014-01-10 21:14
I had the same issue few days ago. I was without my NFC tags so I needed to do a hard reboot on my phone and ended up uninstalling the app because it happened a few times.
I'm also unable to reproduce it but I saw the same symptoms as @damacus pointed out, it self activated after few hours iddle.
Getting home today I'll try to reinstall the app to try to reproduce it once again.

BTW, I'm using a Razr i with stock 4.1.2

**Comment by BitterrootBrute** [comment] 2014-01-11 14:33
I also had this issue with my HTC One GPE 4.4.2. The app did have use with no lockscreen checked but the app was inactive and I had reverted back to using a PIN. Having no programmed tags with me when it occurred I had to hard reboot. Happened about three or four times and I've since started carrying a programmed rag jic.

**Comment by xxv** [comment] 2014-01-15 00:39
I just had this happen to me. I have nfc unlock set to inactive, but otherwise integrated into the system. I use face unlock with a PIN fallback. I was able to trigger this behavior by failing the face unlock and then triggering an invalid PIN message. The NFC Unlock lockscreen popped up over my normal lockscreen. I tried to activate the NFC Unlock PIN window, but it didn't work. I eventually managed to type my PIN into the system lockscreen by carefully timing when I pressed it's buttons (every time I tried to activate the NFC Unlock PIN entry the system lockscreen flashed briefly.)

**Comment by JohnMcLear** [comment] 2014-01-15 00:40
Good spot @xxv @r2DoesInc any ideas now?

**Comment by Ohelig** [comment] 2014-01-17 21:15
Using a Galaxy S3 CleanROM 6.0 R2 (Android 4.1.2), I also have this problem after failing the pattern unlock. Sometimes I get to the NFC Ring Unlock screen several times (I swipe it away and another one is behind it)

I'll try to get a video if you want.

**Comment by LittleJohnD** [comment] 2014-01-18 17:36
I also found this to be an issue I initially thought it to be sporadic but it has always been after a failed pattern attempt. However a swipe to the left will allow it to pass, as I have no tag

**Comment by mougino** [comment] 2014-01-23 09:55
It happened to me just this morning, after 3-4 days with the unlock app set "inactive" (but a password protection), the NFC Ring Unlock screen triggered out of a failed password attempt (and as I didn't have the ring on me, like @fgsguedes I couldn't use my phone at all). I use a Sony Xperia Z with Android 4.2.2. I tried a few times and could replicate: bad password, then good password > NFC Ring Unlock screen.

**Comment by JohnMcLear** [comment] 2014-01-23 12:51
@r2DoesInc sounds like this is way more common than we first anticipated, is a fix scheduled in our next bug fix run mid Feb?

**Comment by r2DoesInc** [comment] 2014-01-23 15:55
Yes it is.

**Comment by JohnMcLear** [comment] 2014-01-26 16:30
A fix is in for this and has been pushed to Play store :)

**Closed as completed by JohnMcLear** 2014-01-26 16:30 UTC
Labels: bug
