### ISSUE TITLE
Disable sound notification

### ISSUE THREAD

**Issue by lemmings67** [mclear/Android_NFC_Ring_Unlock#106] opened 2014-07-23 12:52 UTC
When your are scanning the ring to unlock, there is a sound notification that indicate that it's unlocked : I want to disable this...

**Comment by JohnMcLear** [comment] 2014-07-23 12:56
Duplicate of https://github.com/mclear/Android_NFC_Ring_Unlock/issues/43

**Closed as completed by JohnMcLear** 2014-07-23 12:56 UTC

**Comment by lemmings67** [comment] 2014-07-23 13:40
I found the solution : use Xposed + NFC LookScreenOff Enabler :+1: http://repo.xposed.info/module/pk.qwerty12.nfclockscreenoffenabler
