### ISSUE TITLE
Unlock app enable even if no unlock key is present

### ISSUE THREAD

**Issue by timemaster67** [mclear/Android_NFC_Ring_Unlock#48] opened 2014-03-01 00:50 UTC
I installed the unlock application to test it even thought I still don't own any nfc thing. I activated the application for fun. I turned off the screen and locked my phone
1. When I turned on my cellphone, the unlock application was there, digilently doing it's job. However there is one problem with this : I had not entered any key to unlock it. 

I know that I am a stupid user that did not take the time to read the notice... but should the app really activate it when there is no unlock keys to make it work???

I know that there is a unlock with google authentification.. but I had the two factor authentification and it did not work... :) kind of screwed. I killed the application from adb to disable it. Seems like from the issue list that I can activate a pin unlock so I will do this in the future.

**Comment by JohnMcLear** [comment] 2014-03-01 01:07
I don't really a know we can win here, the notice is there to prevent exactly this from happening..  The Pin isn't compulsory, making it compulsory would potentially reduce security.  Maybe we shouldn't allow it to be enabled if two factor auth is installed?  Or even better, we support 2 factor auth in the future which would make this a dupe of https://github.com/mclear/Android_NFC_Ring_Unlock/issues/7 ?

**Comment by timemaster67** [comment] 2014-03-01 06:11
ok so I think it is now clean that the user was in problem : "the notice is there to prevent exactly this from happening" because I did not see/remember a notice telling me "if you enable the lock but don't have keys setup you won't be able to unlock your phone".

**Comment by r2DoesInc** [comment] 2014-06-02 16:14
resolved

**Closed as completed by r2DoesInc** 2014-06-02 16:14 UTC
Labels: enhancement
