### ISSUE TITLE
Better Feedback For Unlock Attempts

### ISSUE THREAD

**Issue by corveroth** [mclear/Android_NFC_Ring_Unlock#98] opened 2014-06-18 20:26 UTC
Rather than, or in addition to, the provided stickers, I would like the option to render my phone's NFC heat-map (as seen in NFC Ring Control) as a background for the lock screen.

Additionally, any non-aural feedback for unsuccessful ring reads would be very useful. In fact, any additional feedback for the unlock process (is there such a thing as "partial" or "weak" detection of a tag that would hint when the ring was near?) would be an improvement.

I think the security of the ring comes from the relatively hard-to-duplicate identity of the physical object - revealing the detection location seems like an acceptable compromise for the sake of usability (and showing it on-screen is hardly any worse than affixing a sticker!).

**Comment by JohnMcLear** [comment] 2014-06-19 18:10
Agreed on heatmap

**Comment by r2DoesInc** [comment] 2014-06-22 12:56
The lockscreen wallpaper can be set. save the heatmap image somewhere and set it as the background.

**Comment by JohnMcLear** [comment] 2014-06-22 14:06
Volume down and power off button will do a print screen, what Ken proposes is an ideal temporary solution..

----- Reply message -----

**Comment by JohnMcLear** [comment] 2014-10-09 11:53
Duplicate of https://github.com/mclear/Android_NFC_Ring_Unlock/issues/103

**Closed as completed by JohnMcLear** 2014-10-09 11:53 UTC
Labels: enhancement
