### ISSUE TITLE
Double unlocking

### ISSUE THREAD

**Issue by xxv** [mclear/Android_NFC_Ring_Unlock#25] opened 2014-01-10 05:13 UTC
Occasionally the app prompts for unlocking twice in a row. I believe it's when the configuration screen is showing and the configuration app locks. I'm not sure, though, as I recall having that happen when I didn't have that app open.

**Comment by r2DoesInc** [comment] 2014-01-10 15:41
Many people have reported similar things fixing it is not really possible with the current code base. They are add side effects aused by some of the fallback watchers. Since changing the lockscreen mechanism in the base NFCSecure app, these services have been discarded, removing the cause of the issue. The changes would be a feature upgrade john would need to consider adding.

**Comment by JohnMcLear** [comment] 2014-01-10 15:44
Sorry but this is a bug and needs resolving without any feature upgrade.

**Closed as completed** 2014-01-27 00:34 UTC
Labels: bug

**Comment by xxv** [comment] 2014-01-27 03:16
I have no idea why this has been closed. The issue remains.

This can be reproduced reliably by doing the following:
1. Configure the unlock app in the following way: PIN unlock is on, NFC unlock is active, one key has been added, Device Administrator is in place, lockscreen features disabled, use with no lockscreen checked. Everything else is the default.
2. Turn off screen.
3. Turn on screen, unlock pops up.
4. Slide unlock fallback slider to the PIN entry. 
5. Press back button.
6. Turn off screen.
7. Turn on screen.
8. Unlock using NFC tag.

Expected:

9# device is fully unlocked.

Actual:

9# lockscreen pops up a second time, requiring re-scanning of the NFC tag.

**Comment by JohnMcLear** [comment] 2014-01-27 14:12
@xxv @r2DoesInc has been going through and closing issues as he is patching them in the repo, we will push out a new APK either today or tomorrow, if I send you through a signed APK would you be happy to test it?  We should really use some testing service but as we don't have the time to get it setup right now that is the best compromise.

**Comment by xxv** [comment] 2014-01-27 15:58
Ah, gotchya. It was my understanding that this bug tracker was for issues on the publicly-released APK.

I'd be happy to be a betatester. Google Play has a built-in betatesting service you could use. See https://support.google.com/googleplay/android-developer/answer/3131213?hl=en for details.

**Comment by JohnMcLear** [comment] 2014-01-27 16:20
well that is lots of awesome..

https://play.google.com/apps/testing/co.mclear.nfcringunlockpro

That's the link to our alpha testing facility thingy..

**Comment by JohnMcLear** [comment] 2014-01-27 16:20
https://groups.google.com/forum/#!forum/nfc-ring-beta-testers/ is the link to our alpha testing google group, you gotta join that first then click on the link to become a beta tester.

**Comment by xxv** [comment] 2014-01-27 16:37
Unfortunately, the link doesn't work yet. Hopefully it becomes active soon!

**Comment by r2DoesInc** [comment] 2014-01-27 17:08
Ya, its a pretty cool feature. They also offer staged roll outs as an
option now which I think is super cool. Allows you to catch bugs while only
on a few devices, giving you a chance to fix them before they get to
everyone.

**Comment by JohnMcLear** [comment] 2014-01-27 17:36
Whoops, think I got something wrong @xxv https://groups.google.com/forum/#!forum/nfc-ring-beta-testers/
